### ISSUE TITLE
Hospitalization rate in NY

### ISSUE THREAD

**Issue by dltacube** [theojulienne/covid-19-graphics#5]
Hey,

Just wanted to mention that the hospitalization rates for new york _might_ be wrong. The page is currently listing 0 cases per day since early June which I thought was too good to be true. I check [here](https://www1.nyc.gov/site/doh/covid/covid-19-goals.page) and it seems like we're still admitting 60-70 COVID patients per day.

Not a huge deal, just thought I'd mention it :)

**Comment by theojulienne** [comment]
The US data comes from covidtracking, it does look like the hospitalisation rate has stopped updating there too: https://covidtracking.com/data/state/new-york 🤔

**Comment by dltacube** [comment]
I shot them an email! Maybe they'll fix it soon.
